version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: some-clickhouse-server
    restart: unless-stopped
    # map internal ClickHouse ports to host for convenience
    ports:
      - "18123:8123"   # HTTP
      - "19000:9000"   # Native TCP
    environment:
      CLICKHOUSE_PASSWORD: "changeme"   # dev only — don't use in prod
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      # init SQL files: mounted into entrypoint init directory
      - ./clickhouse/init:/docker-entrypoint-initdb.d:ro
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS --max-time 3 http://127.0.0.1:8123/ || exit 1"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    # depends_on:
    #   clickhouse:
    #     condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - grafana_storage:/var/lib/grafana
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/login || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6

  # Example placeholder for your application (commented out until you have Dockerfile)
  # app:
  #   build: ./app
  #   container_name: my-app
  #   restart: unless-stopped
  #   depends_on:
  #     - clickhouse
  #   environment:
  #     CLICKHOUSE_HOST: clickhouse
  #     CLICKHOUSE_PORT: 9000
  #     CLICKHOUSE_USER: default
  #     CLICKHOUSE_PASSWORD: changeme

volumes:
  clickhouse_data:
  clickhouse_logs:
  grafana_storage:

